name: pvp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
      - opencv-python
      - imageio
      - imageio-ffmpeg
      - ipdb
      - timm
      - configargparse
      - einops
      - tensorboardX
  - scipy
  - numpy
  - matplotlib
  - pytorch==1.12.1
  - torchvision==0.13.1
  - tqdm
  - cudatoolkit==11.3.1
  - pytorch-lightning=1.8.1
  - torchmetrics=0.11.1
  - hydra-core=1.3.1
  - rich=12.6.0